package interfaceee;
//1.INTERFACE METHODS ARE BY DEFAULT PUBLIC AND ABSTARCT
//2.INTERFACE VARIABLES ARE BYDEFALUT PUBLIC STATIC AND FINAL
//3.INTERFACE METHOD MUST BE OVERRIDEN INSIDE THA IMPLEMENTING CLASSES
//4.INTERFACE NOTHING BUT DEALS BETWEEN CLIENT AND DEVELOPER
public interface interface1 {
	void display();
	void fun();

}
